---
- hosts: my_target_hosts
  become: yes

  tasks:
    - name: Install Apache, MySQL, and PHP
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
        state: latest

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes
...
